/* eslint-disable jest/valid-expect */
import reduxState from "../reducers/persReducer";
import expect from "expect";

test("debe regresar estado inicial", () => {
	expect(reduxState(undefined, {})).toEqual({
		pers: [],
		favcount: 0,
		perscount: 0,
		error: null,
		loading: false,
	});
});

test("debe agregar personaje a estado", () => {
	const state = {
		pers: [
			{
				name: "Harry Potter",
				species: "human",
				gender: "male",
				house: "Gryffindor",
				dateOfBirth: "31-07-1980",
				yearOfBirth: 1980,
				ancestry: "half-blood",
				eyeColour: "green",
				hairColour: "black",
				wand: {
					wood: "holly",
					core: "phoenix feather",
					length: 11,
				},
				patronus: "stag",
				hogwartsStudent: true,
				hogwartsStaff: false,
				actor: "Daniel Radcliffe",
				alive: true,
				image: "http://hp-api.herokuapp.com/images/harry.jpg",
			},
			{
				name: "Hermione Granger",
				species: "human",
				gender: "female",
				house: "Gryffindor",
				dateOfBirth: "19-09-1979",
				yearOfBirth: 1979,
				ancestry: "muggleborn",
				eyeColour: "brown",
				hairColour: "brown",
				wand: {
					wood: "vine",
					core: "dragon heartstring",
					length: "",
				},
				patronus: "otter",
				hogwartsStudent: true,
				hogwartsStaff: false,
				actor: "Emma Watson",
				alive: true,
				image: "http://hp-api.herokuapp.com/images/hermione.jpeg",
			},
		],
		favcount: 0,
		perscount: 2,
		error: null,
		loading: false,
	};
	const type = "BUSCAR_PERS_SUCCESS";
	const payload = [
		{
			name: "Ron Weasley",
			species: "human",
			gender: "male",
			house: "Gryffindor",
			dateOfBirth: "01-03-1980",
			yearOfBirth: 1980,
			ancestry: "pure-blood",
			eyeColour: "blue",
			hairColour: "red",
			wand: {
				wood: "willow",
				core: "unicorn tail-hair",
				length: 14,
			},
			patronus: "Jack Russell terrier",
			hogwartsStudent: true,
			hogwartsStaff: false,
			actor: "Rupert Grint",
			alive: true,
			image: "http://hp-api.herokuapp.com/images/ron.jpg",
		},
	];

	expect(reduxState(state, { type, payload })).toEqual({
		pers: [
			{
				name: "Harry Potter",
				species: "human",
				gender: "male",
				house: "Gryffindor",
				dateOfBirth: "31-07-1980",
				yearOfBirth: 1980,
				ancestry: "half-blood",
				eyeColour: "green",
				hairColour: "black",
				wand: {
					wood: "holly",
					core: "phoenix feather",
					length: 11,
				},
				patronus: "stag",
				hogwartsStudent: true,
				hogwartsStaff: false,
				actor: "Daniel Radcliffe",
				alive: true,
				image: "http://hp-api.herokuapp.com/images/harry.jpg",
			},
			{
				name: "Hermione Granger",
				species: "human",
				gender: "female",
				house: "Gryffindor",
				dateOfBirth: "19-09-1979",
				yearOfBirth: 1979,
				ancestry: "muggleborn",
				eyeColour: "brown",
				hairColour: "brown",
				wand: {
					wood: "vine",
					core: "dragon heartstring",
					length: "",
				},
				patronus: "otter",
				hogwartsStudent: true,
				hogwartsStaff: false,
				actor: "Emma Watson",
				alive: true,
				image: "http://hp-api.herokuapp.com/images/hermione.jpeg",
			},
			{
				name: "Ron Weasley",
				species: "human",
				gender: "male",
				house: "Gryffindor",
				dateOfBirth: "01-03-1980",
				yearOfBirth: 1980,
				ancestry: "pure-blood",
				eyeColour: "blue",
				hairColour: "red",
				wand: {
					wood: "willow",
					core: "unicorn tail-hair",
					length: 14,
				},
				patronus: "Jack Russell terrier",
				hogwartsStudent: true,
				hogwartsStaff: false,
				actor: "Rupert Grint",
				alive: true,
				image: "http://hp-api.herokuapp.com/images/ron.jpg",
			},
		],
		favcount: 0,
		perscount: 3,
		error: null,
		loading: false,
	});
});

test("debe poner personaje en favoritos", () => {
	const state = {
		pers: [
			{
				id: 1,
				name: "Harry Potter",
				species: "human",
				gender: "male",
				house: "Gryffindor",
				dateOfBirth: "31-07-1980",
				yearOfBirth: 1980,
				ancestry: "half-blood",
				eyeColour: "green",
				hairColour: "black",
				patronus: "stag",
				hogwartsStudent: true,
				hogwartsStaff: false,
				actor: "Daniel Radcliffe",
				alive: true,
				image: "http://hp-api.herokuapp.com/images/harry.jpg",
				favorite: false,
			},
			{
				id: 2,
				name: "Hermione Granger",
				species: "human",
				gender: "female",
				house: "Gryffindor",
				dateOfBirth: "19-09-1979",
				yearOfBirth: 1979,
				ancestry: "muggleborn",
				eyeColour: "brown",
				hairColour: "brown",
				patronus: "otter",
				hogwartsStudent: true,
				hogwartsStaff: false,
				actor: "Emma Watson",
				alive: true,
				image: "http://hp-api.herokuapp.com/images/hermione.jpeg",
				favorite: false,
			},
		],
		favcount: 0,
		perscount: 2,
		error: null,
		loading: false,
	};
	const type = "SET_FAVORITE";
	const payload = {
		id: 2,
		value: true,
	};
	expect(reduxState(state, { type, payload })).toEqual({
		pers: [
			{
				id: 1,
				name: "Harry Potter",
				species: "human",
				gender: "male",
				house: "Gryffindor",
				dateOfBirth: "31-07-1980",
				yearOfBirth: 1980,
				ancestry: "half-blood",
				eyeColour: "green",
				hairColour: "black",
				patronus: "stag",
				hogwartsStudent: true,
				hogwartsStaff: false,
				actor: "Daniel Radcliffe",
				alive: true,
				image: "http://hp-api.herokuapp.com/images/harry.jpg",
				favorite: false,
			},
			{
				id: 2,
				name: "Hermione Granger",
				species: "human",
				gender: "female",
				house: "Gryffindor",
				dateOfBirth: "19-09-1979",
				yearOfBirth: 1979,
				ancestry: "muggleborn",
				eyeColour: "brown",
				hairColour: "brown",
				patronus: "otter",
				hogwartsStudent: true,
				hogwartsStaff: false,
				actor: "Emma Watson",
				alive: true,
				image: "http://hp-api.herokuapp.com/images/hermione.jpeg",
				favorite: true,
			},
		],
		favcount: 1,
		perscount: 2,
		error: null,
		loading: false,
	});
});
